from flask import Flask, render_template, request, send_from_directory
from hash_utils import generate_hash
from datetime import datetime
from blockchain_config import web3, contract
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from pyzbar.pyzbar import decode
from PIL import Image
import os
import json
import qrcode

app = Flask(__name__)

UPLOAD_FOLDER = 'uploads'

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def load_blockchain():

    try:

        with open('blockchain.json', 'r') as file:

            return json.load(file)

    except:

        return []

def save_blockchain(blockchain_data):

    with open('blockchain.json', 'w') as file:

        json.dump(
            blockchain_data,
            file,
            indent=4
        )

def create_report(filename, file_hash):

    blockchain = load_blockchain()

    timestamp = "Unknown"

    for block in blockchain:

        if block["filename"] == filename:

            timestamp = block["timestamp"]

            break

    report_filename = f"{filename}_report.pdf"

    report_path = os.path.join(
        'reports',
        report_filename
    )

    pdf = SimpleDocTemplate(report_path)

    styles = getSampleStyleSheet()

    content = []

    title = Paragraph(
        "<b>DOCUMENT AUTHENTICATION REPORT</b>",
        styles['Title']
    )

    content.append(title)

    content.append(Spacer(1, 20))

    lines = [

        f"<b>Generated By:</b> Shield Squad",

        f"<b>File Name:</b> {filename}",

        f"<b>Timestamp:</b> {timestamp}",

        f"<b>SHA-256 Hash:</b> {file_hash}",

        f"<b>Verification Status:</b> AUTHENTIC",

        f"<b>Blockchain Security:</b> ACTIVE",

        f"<b>Web3 Verification:</b> ENABLED"
    ]

    for line in lines:

        paragraph = Paragraph(
            line,
            styles['BodyText']
        )

        content.append(paragraph)

        content.append(Spacer(1, 12))

    pdf.build(content)

    return report_filename

def analyze_document(file):

    risky_extensions = [
        '.exe',
        '.bat',
        '.js',
        '.apk'
    ]

    filename = file.filename.lower()

    risk_level = "LOW RISK ✅"

    if any(
        filename.endswith(ext)
        for ext in risky_extensions
    ):

        risk_level = "HIGH RISK ⚠️"

    return risk_level

def sync_nodes(blockchain):

    node_files = [

        'node1.json',
        'node2.json',
        'node3.json'
    ]

    for node in node_files:

        with open(node, 'w') as file:

            json.dump(
                blockchain,
                file,
                indent=4
            )

@app.route('/')

def home():

    blockchain = load_blockchain()

    return render_template(
        'index.html',
        blockchain=blockchain
    )

@app.route('/upload', methods=['POST'])

def upload_file():

    file = request.files['document']

    if file:

        filepath = os.path.join(
            app.config['UPLOAD_FOLDER'],
            file.filename
        )

        file.save(filepath)

        file_hash = generate_hash(filepath)

        risk_level = analyze_document(file)

        blockchain = load_blockchain()

        previous_hash = "0000"

        if len(blockchain) > 0:

            previous_hash = blockchain[-1]['current_hash']

        block = {

            'index': len(blockchain) + 1,

            'filename': file.filename,

            'timestamp': datetime.now().strftime(
                "%d-%m-%Y %I:%M:%S %p"
            ),

            'previous_hash': previous_hash,

            'current_hash': file_hash
        }

        blockchain.append(block)

        save_blockchain(blockchain)

        sync_nodes(blockchain)

        account = web3.eth.accounts[0]

        tx_hash = contract.functions.uploadDocument(

            file.filename,
            file_hash

        ).transact({

            'from': account

        })

        web3.eth.wait_for_transaction_receipt(
            tx_hash
        )

        qr_data = f"""
        Document Name: {file.filename}

        SHA-256 Hash:
        {file_hash}
        """

        qr = qrcode.make(qr_data)

        qr_filename = f"{file.filename}.png"

        qr_path = os.path.join(
            'static/qrcodes',
            qr_filename
        )

        qr.save(qr_path)

        report_file = create_report(
            file.filename,
            file_hash
        )

        return render_template(

            'result.html',

            file_hash=file_hash,

            qr_file=qr_filename,

            report_file=report_file,

            risk_level=risk_level

        )

    return "File Upload Failed"

@app.route('/verify', methods=['POST'])

def verify_file():

    file = request.files['document']

    if file:

        filepath = os.path.join(
            app.config['UPLOAD_FOLDER'],
            file.filename
        )

        file.save(filepath)

        new_hash = generate_hash(filepath)

        blockchain = load_blockchain()

        original_hash = None

        for block in blockchain:

            if block['filename'] == file.filename:

                original_hash = block['current_hash']

        if original_hash == new_hash:

            return render_template(
                'verify_result.html',
                status="authentic"
            )

        else:

            return render_template(
                'verify_result.html',
                status="tampered"
            )

    return "Verification Failed"

@app.route('/blockchain')

def blockchain_page():

    blockchain = load_blockchain()

    return render_template(
        'blockchain.html',
        blockchain=blockchain
    )

@app.route('/qrcodes')

def qr_gallery():

    qr_folder = 'static/qrcodes'

    qr_images = os.listdir(qr_folder)

    return render_template(
        'qrcodes.html',
        qr_images=qr_images
    )

@app.route('/download-report/<filename>')

def download_report(filename):

    return send_from_directory(
        'reports',
        filename,
        as_attachment=True
    )

@app.route('/generate-report', methods=['GET', 'POST'])

def generate_report():

    message = None

    if request.method == 'POST':

        file = request.files['document']

        blockchain = load_blockchain()

        found = False

        for block in blockchain:

            if block['filename'] == file.filename:

                found = True

                report_file = create_report(

                    block['filename'],
                    block['current_hash']

                )

                return render_template(

                    'report_result.html',

                    report_file=report_file

                )

        if not found:

            message = """
            Please upload your document first.
            """

    return render_template(

        'generate_report.html',

        message=message

    )

@app.route('/nodes')

def nodes():

    return render_template(
        'nodes.html'
    )

@app.route('/verify-qr', methods=['GET', 'POST'])

def verify_qr():

    result = None

    if request.method == 'POST':

        qr_file = request.files['qr_image']

        qr_path = os.path.join(
            'uploads',
            qr_file.filename
        )

        qr_file.save(qr_path)

        image = Image.open(qr_path)

        decoded_objects = decode(image)

        if decoded_objects:

            qr_data = decoded_objects[0].data.decode(
                'utf-8'
            )

            blockchain = load_blockchain()

            for block in blockchain:

                if block['current_hash'] in qr_data:

                    result = f"""
                    AUTHENTIC DOCUMENT

                    File:
                    {block['filename']}

                    Hash:
                    {block['current_hash']}
                    """

                    break

            if not result:

                result = """
                INVALID QR CODE
                """

        else:

            result = """
            QR CODE NOT DETECTED
            """

    return render_template(
        'verify_qr.html',
        result=result
    )

@app.route('/verify-hash', methods=['GET', 'POST'])

def verify_hash():

    result = None

    if request.method == 'POST':

        entered_hash = request.form['hash'].strip()

        blockchain = load_blockchain()

        found = False

        for block in blockchain:

            if block['current_hash'] == entered_hash:

                found = True

                result = f"""
                AUTHENTIC HASH VERIFIED

                File:
                {block['filename']}

                Timestamp:
                {block['timestamp']}

                Block Number:
                {block['index']}
                """

                break

        if not found:

            result = """
            INVALID OR UNKNOWN HASH
            """

    return render_template(
        'verify_hash.html',
        result=result
    )

if __name__ == '__main__':

    app.run(debug=True)